#! /bin/sh

sxhkd &

killall polybar
polybar future &
pulseaudio &
rmmod pcspkr & 
wal -i /home/lester/Pictures/miami.jpg -n & 
feh --bg-scale '/home/lester/Pictures/miami.jpg' & 
compton --config /home/lester/.config/compton/compton.conf -b &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
